### ISSUE TITLE
(Fix) display empty card of company type for xDai chain 

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/oracles-dapps-validators#101]
**Problem**: Empty company-validator cards are of user type in xDai chain
![screen shot 2018-12-20 at 16 59 27](https://user-images.githubusercontent.com/4341812/50292651-b9bde400-0482-11e9-977f-275001dfba07.png)

**Solution**: Display corresponding company attributes for xDai chain for empty cards.

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/poa-dapps-validators/pull/102.
