### ISSUE TITLE
Network switcher is not displayed

### ISSUE THREAD

**Issue by varasev** [oraclesorg/oracles-dapps-validators#106]
In an old version of the `Validators DApp` we had a network switcher at the top right corner which allowed us to switch between networks if MetaMask is not installed: https://github.com/poanetwork/poa-dapps-validators/blob/35d64a8dac3bd9d818e42f88153943f96de17518/src/index.js#L234-L244

Please return this switcher back. It seemed to be removed with the latest changes made in January 2019.

**Comment by igorbarinov** [comment]
I also miss it

**Comment by gabitoesmiapodo** [comment]
I'll have a look.

I think it wasn't present on the designs and it was removed.

**Comment by varasev** [comment]
@gabitoesmiapodo Yes, it should only be displayed when MetaMask is not installed (missed that on UI layouts).
