### ISSUE TITLE
Confirm and Finalize buttons don't work on the `Pending Changes` page

### ISSUE THREAD

**Issue by varasev** [oraclesorg/oracles-dapps-validators#108]
We have a pending change for Kovan network: https://validators.poa.network/poa-dapps-validators/pending-changes

![image](https://user-images.githubusercontent.com/33550681/57795197-0960bd00-774e-11e9-8cab-e43fc533af1d.png)

When clicking on the `Confirm` or `Finalize` button the `miningkey` attribute is empty for some reason: https://github.com/poanetwork/poa-dapps-validators/blob/ff6726a4f2034324288e22a6ffc41a15e79b8a1c/src/index.js#L138

It is set on the line https://github.com/poanetwork/poa-dapps-validators/blob/ff6726a4f2034324288e22a6ffc41a15e79b8a1c/src/components/AllValidators/index.js#L162 where it is not empty.

@gabitoesmiapodo any idea how to fix this?

**Comment by gabitoesmiapodo** [comment]
@varasev Not really, but I could look into it.

Any way I could test this locally?

**Comment by varasev** [comment]
You can just `console.log` the miningKey when clicking the button.
