### ISSUE TITLE
Unexpected token : In JSON at position 3 when open https://validators.poa.network/

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/oracles-dapps-validators#120]
When open https://validators.poa.network
<img width="1269" alt="Screen Shot 2020-03-24 at 5 56 45 PM" src="https://user-images.githubusercontent.com/424628/77454679-27c92780-6df9-11ea-83d9-1bc12a48849f.png">

can be related to Nethermind as RPC nodes

<img width="1392" alt="Screen Shot 2020-03-24 at 6 03 59 PM" src="https://user-images.githubusercontent.com/424628/77455251-e7b67480-6df9-11ea-8105-4d8d3cf572c5.png">

**Comment by varasev** [comment]
Fixed in https://github.com/poanetwork/poa-dapps-validators/pull/121 and https://github.com/poanetwork/poa-dapps-voting/pull/217.
