### ISSUE TITLE
(Fix) Hard code MoC metadata

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/oracles-dapps-validators#19]
Problem: MoC metadata is not showing in DApp
Solution: Hardcode MoC metadata

**Comment by vbaranov** [comment]
Fix is not yet deployed on github pages https://poanetwork.github.io/poa-dapps-validators/. Maybe we can add automation with Travis CI after successful PR merging on core branch?

**Comment by igorbarinov** [comment]
we are using Netlify now. @rstormsf has an idea to differentiate RPCs (network) by domain name when we don't use web3 injection (metamask).
URLs for deployments: 
https://core-validators.poa.network/
https://sokol-validators.poa.network/
both are deployed from `core` branch. 
We plant to get rid of `core` and `sokol` branches in DApps and will work in the master branch. @rstormsf please merge last changes into master branch when we are ready for it.


About notifications:
I added GitHub hooks from netlify and we'll get information about deployed and failed.
Also, I created a channel in our messenger #prj-dapps-governace with notifications from netlify.

**Comment by rstormsf** [comment]
It's already been done. 
I'll remove sokol branch right now

**Comment by igorbarinov** [comment]
@rstormsf can I replace `core-validators.poa.network` and `sokol-validators.poa.network` to `validators.poa.network` ?

**Comment by rstormsf** [comment]
@igorbarinov no. because if there is no metamask, that's how it will be able to differentiate between networks. Only this Dapp handles it. Maybe we can also enable other Dapps to be able to work without metamask using the same pattern.

**Comment by igorbarinov** [comment]
why does it require to use MM now?
https://cl.ly/3f1g2J0F1F0w

**Comment by rstormsf** [comment]
@igorbarinov 
Fix your browser, I don't have such issues

**Comment by rstormsf** [comment]
![image](https://user-images.githubusercontent.com/9360827/35254765-84ede780-ffa0-11e7-9df7-ecbe02eca722.png)

**Comment by igorbarinov** [comment]
https://cl.ly/3t3U270x371R

**Comment by igorbarinov** [comment]
If no MM installed it shows validators
If MM installed and unlocked it shows validators
If MM installed and not unlocked/configured it shows alert

**Comment by rstormsf** [comment]
so? @igorbarinov 
read alert message.

**Comment by igorbarinov** [comment]
For me expected behavior with locked MM should be like there is no MM installed

**Comment by rstormsf** [comment]
you are on the wrong network id

**Comment by rstormsf** [comment]
https://github.com/poanetwork/poa-dapps-validators/pull/32 
@igorbarinov

**Comment by rstormsf** [comment]
#33 
@igorbarinov 
Deployed: https://poanetwork.github.io/poa-dapps-validators/
Thank you for your points. I have fixed it

**Comment by igorbarinov** [comment]
🤝
