### ISSUE TITLE
Able to view and set Validator MetaData with arbitrary account ( should this only work for valid votiing key )

### ISSUE THREAD

**Issue by johnnynuuma** [oraclesorg/oracles-dapps-validators#29]
Sokol:  https://sokol-validators.poa.network

Seems like I can access the Validator MetaData page and click "SET METADATA" with a random Sokol account.

I didn't try to "SET METADATA", as transaction will likely fail.

![screenshot from 2018-01-21 11-55-21](https://user-images.githubusercontent.com/22530182/35198354-7e786118-fea2-11e7-99ad-be7a3dbcbb60.png)

![screenshot from 2018-01-21 11-59-38](https://user-images.githubusercontent.com/22530182/35198362-9e42ef7c-fea2-11e7-9b01-a1b0dfd381fc.png)

**Comment by rstormsf** [comment]
Good catch! we will make this improvement

**Comment by varasev** [comment]
Fixed in https://github.com/poanetwork/poa-dapps-validators/pull/69.
