### ISSUE TITLE
(Bug) MetaMask is locked alert, but it is not locked 

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/oracles-dapps-validators#39]
![ezgif-4-e39bbf44f6](https://user-images.githubusercontent.com/4341812/35617476-5cd7e97c-0689-11e8-84bc-05b05cefb4df.gif)
![screen shot 2018-01-31 at 13 20 18](https://user-images.githubusercontent.com/4341812/35617550-8e374d32-0689-11e8-889f-78d9b95e464c.png)

**Comment by varasev** [comment]
Fixed in https://github.com/poanetwork/poa-dapps-validators/pull/66.
