### ISSUE TITLE
UX/UI - Hide "Pending Change Requested Date" row if there is no date to show 

### ISSUE THREAD

**Issue by SiddigZeidan** [oraclesorg/oracles-dapps-validators#60]
Currently, on the DApp, the "Pending Change Requested Date" is displayed even when there is no date. This should be only visible if there is info there.

The wording of that row should also change, as `Pending Change Requested Date` doesn't make sense. I suggest removing the word "requested" so its just `Pending change date`. @igorbarinov  thoughts?

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/poa-dapps-validators/pull/68.
