### ISSUE TITLE
(Bug) confirmation and finalization txs with invalid voting key

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/oracles-dapps-validators#72]
**Problem**: transactions to confirm and finalize are sent to blockchain even if a user unlocks invalid voting key

**Solution**: show alert on clicking to the corresponding buttons, that the current unlocked voting key is invalid

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/poa-dapps-validators/pull/94.
