### ISSUE TITLE
(Feature) Render validators' registered (unconfirmed) physical address from PoPA

### ISSUE THREAD

**Issue by unjapones** [oraclesorg/oracles-dapps-validators#78]
The PR that implements [#74](https://github.com/poanetwork/poa-dapps-validators/issues/74) only retrieves & renders a confirmed address from PoPA. This issue covers retrieving & rendering a **registered (unconfirmed)** address.

This also aims to prioritize the address information. The following list may represent the order of how _reliable_ the information is:

1. Confirmed physical address from PoPA.
2. Registered (unconfirmed) address from PoPA.
3. Already existing address from `ValidatorMetadata.sol` (fallback scenario, meant to be deprecated/dropped/hidden?)

How this is prioritization is represented on the UI needs to be defined.

**Comment by unjapones** [comment]
Assigned the people that may be involved in the definitions of this ticket, following the suggestions of [this comment](https://github.com/poanetwork/poa-dapps-validators/issues/74#issuecomment-416305645). Sorry in advance for the spam.

**Comment by varasev** [comment]
I think we should display address information for each validator in the following manner:

- First of all, display all confirmed addresses from PoPA contract for each validator. If there is at least one confirmed address, don't display unconfirmed addresses from PoPA and address from ValidatorMetadata.

- If there are no confirmed addresses from PoPA, display unconfirmed addresses from PoPA but with `Unconfirmed` label. If there is at least one unconfirmed address, don't display an address from ValidatorMetadata.

- If there are no confirmed or unconfirmed addresses from PoPA, display the address from `ValidatorMetadata` contract (fallback scenario) with the same `Unconfirmed` label.

I suggest to represent the list of addresses in the following manner:

**Example for confirmed addresses from PoPA:** 
![1](https://user-images.githubusercontent.com/33550681/44845696-ec836880-ac56-11e8-8f4f-b2638dcbc7af.png)

**Example for unconfirmed addresses from PoPA:** 
![2](https://user-images.githubusercontent.com/33550681/44845706-f311e000-ac56-11e8-8637-6a63046c6bfd.png)

**Example for unconfirmed address from ValidatorMetadata:** 
![3](https://user-images.githubusercontent.com/33550681/44845718-f907c100-ac56-11e8-8297-40cec681decd.png)

If there is only one address (either confirmed or not), don't display `#1`, as on the last screen.

Also, we should remove the displaying of `State` and `Zip Code` rows and display state and zip code inside `Confirmed Address` or `Unconfirmed Address` row, separating those from the address with a comma, as it's shown on the screens above.

Does anyone have some other thoughts or suggestions?

**Comment by igorbarinov** [comment]
Vadim, I like your idea. Could we have information about token/ token registry on hover?
e.g. like we have in the bridge https://cl.ly/9b5d30ad0a8d

**Comment by varasev** [comment]
@igorbarinov Could you specify exact information that we should display about token/ registry?

I see that `EthereumClaimsRegistry` contract stores `confirmation block number`.

`ProofOfPhysicalAddress` contract stores physical addresses and `creation block number`/ `confirmation sha3 code` for each physical address.

**Comment by vbaranov** [comment]
I like the proposal☝️. My 50 POA wei to it:

1. `Unconfirmed/confirmed` takes a lot of space - it could be changed to badges as it proposed in original issue https://github.com/poanetwork/poa-dapps-validators/issues/74#issue-351271440 (though it will take some work from a designer)
2. There is no reason to copy `Address` at every line
3. I'm not sure, do we need a counter for those addresses?

Proposed compact view of card with multiple addresses could looks like this:
![2018-08-31 12 59 52](https://user-images.githubusercontent.com/4341812/44906530-d68cab00-ad1d-11e8-8f67-cf7200e42e09.png)

Proposed view for a card with a single address:
![2018-08-31 13 09 12](https://user-images.githubusercontent.com/4341812/44906966-1902b780-ad1f-11e8-8187-1f7ff967118e.png)

**Comment by pashagonchar** [comment]
**Zeplin:**https://zpl.io/2jw7P46
![poa_validators_1](https://user-images.githubusercontent.com/16716926/44909914-d5fa1180-ad29-11e8-8e45-c248ca401020.png)

**Comment by unjapones** [comment]
@pashagonchar I believe each Address item is comprised of `Street + State + Zip Code`, and they don't have a State and Zip Code in common (like the mockups that @varasev posted on his 1st comment), should we update the Zeplin?

**Comment by pashagonchar** [comment]
@unjapones **Zeplin:** https://zpl.io/2jw7P46
![poa_validators_1](https://user-images.githubusercontent.com/16716926/44923453-f093b100-ad50-11e8-86e8-6542409b294a.png)

**Comment by varasev** [comment]
Let's display the addresses as it's shown in [the comment above](https://github.com/poanetwork/poa-dapps-validators/issues/78#issuecomment-417711992) but remove `State` and `Zip Code` rows.

@igorbarinov @vbaranov Do you think we should display confirmed addresses along with unconfirmed ones as it's shown in [that comment](https://github.com/poanetwork/poa-dapps-validators/issues/78#issuecomment-417711992)? Or the logic described [here](https://github.com/poanetwork/poa-dapps-validators/issues/78#issuecomment-417268863) should be implemented?

**Comment by vbaranov** [comment]
@varasev I would suggest displaying as much info from POPA DApp as we have. So I vote to display both: confirmed and unconfirmed addresses.

**Comment by igorbarinov** [comment]
I agree that we should display as much information as possible from POPA Dapp. For some apps, like bridge, it was important to hide some information because it was not important for end users. Users of validators dapp will use it to get as much information about validators as possible.

**Comment by varasev** [comment]
@unjapones Well, let's display both confirmed and unconfirmed addresses from PoPA then, as it's shown [here](https://github.com/poanetwork/poa-dapps-validators/issues/78#issuecomment-417711992) (without `State` and `Zip Code` rows). The address from `ValidatorMetadata` should only be displayed if there are no addresses for validator in PoPA contract (as a fallback scenario).

**Comment by unjapones** [comment]
@varasev @igorbarinov @vbaranov since we agreed to show the address from `ValidatorMetadata` as _unregistered and as a fallback scenario_, then the form to set the Metadata of a validator will _still_ show the corresponding fields.

Do we want to add a link to the PoPA DApp on the set Metadata form and/or hide its address fields? this is the 3rd item that @pablofullana originally described in #74 

P/s: we should probably discuss this in #79

**Comment by varasev** [comment]
Answered here: https://github.com/poanetwork/poa-dapps-validators/issues/79#issuecomment-418414058
