### ISSUE TITLE
(Feature) Drop or Deprecate validators' address info from ValidatorMetadata.sol

### ISSUE THREAD

**Issue by unjapones** [oraclesorg/oracles-dapps-validators#79]
Assuming the prioritization in issue #78 has been made, this issue covers, either:

* "_Stop showing the physical address metadata from `ValidatorMetadata.sol`_" (i.e. drop its usage) and **remove/hide the corresponding set Metadata form fields + a link to the PoPA DApp**, or...
* "_Still show the physical address metadata from `ValidatorMetadata.sol` but highlight the fact that it ~has a low priority information~ is unconfirmed_" (i.e. eventually deprecate its usage).

After the decision has been made, update the description of the ticket with more detailed requirements.

**Comment by varasev** [comment]
I've described my proposal here: https://github.com/poanetwork/poa-dapps-validators/issues/78#issuecomment-417268863

**Comment by varasev** [comment]
> "Still show the physical address metadata from ValidatorMetadata.sol but highlight the fact that it has a low priority information is unconfirmed" (i.e. eventually deprecate its usage).

I think this one is correct. We'll remove address text fields in that form later when validators register and confirm their addresses with PoPA.

**Comment by unjapones** [comment]
Closing this: the chosen approach was the 2nd option on the description of the issue.
