### ISSUE TITLE
(Fix) Replace logos to POA Network

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/oracles-dapps-validators#9]
Problem: logos refer to Oracles
Solution: replace to POA https://transfer.sh/VS5lp/Archive.zip

**Comment by vbaranov** [comment]
@igorbarinov Archive contains updated images for header only. I need new images for footer too.
Current footer images: [Archive.zip](https://github.com/oraclesorg/poa-dapps-validators/files/1561749/Archive.zip)

**Comment by igorbarinov** [comment]
[Archive 3.zip](https://github.com/oraclesorg/poa-dapps-validators/files/1562976/Archive.3.zip)

**Comment by vbaranov** [comment]
Implemented here: https://github.com/oraclesorg/poa-dapps-validators/pull/10
