### ISSUE TITLE
(Update) New style for xDai Network

### ISSUE THREAD

**Issue by varasev** [oraclesorg/oracles-dapps-validators#97]
We need to have separate colors and logo for xDai network in Validators DApp. Example (yellow-orange color scheme): https://blockscout.com/poa/dai

**Comment by pashagonchar** [comment]
@varasev 

Update

![xdai_governance_app_new_ballot_3](https://user-images.githubusercontent.com/16716926/49885390-c79ab600-fe3f-11e8-93ae-c6f7afc928aa.png)
![xdai_governance_app_new_ballot](https://user-images.githubusercontent.com/16716926/49885391-c8334c80-fe3f-11e8-8c3b-3d8e1f57b11c.png)
![xdai_governance_app](https://user-images.githubusercontent.com/16716926/49885392-c8334c80-fe3f-11e8-8bc1-98c177eb940e.png)

Zeplin

https://zpl.io/V0R9rpl

https://zpl.io/2EPm4Ry

https://zpl.io/adrxKYe

**Comment by varasev** [comment]
These screens are for Voting DApp (not for Validators DApp) 👆 Please attach relevant ones.

**Comment by pashagonchar** [comment]
@varasev Sorry, I'll add

**Comment by pashagonchar** [comment]
@gabitoesmiapodo 

Zeplin

https://zpl.io/beoOwkY

https://zpl.io/2vKAM0v

![xdai_validators_1](https://user-images.githubusercontent.com/16716926/50767987-8901eb00-1287-11e9-83bd-6f5abac03a5c.png)
![xdai_validators_2_1](https://user-images.githubusercontent.com/16716926/50767988-899a8180-1287-11e9-84be-08c079358985.png)

**Comment by gabitoesmiapodo** [comment]
@varasev @vbaranov 

Could you update my permissions for this repo? Same problem as in https://github.com/poanetwork/poa-dapps-voting/issues/187#issuecomment-447943772

**Comment by igorbarinov** [comment]
@gabitoesmiapodo I've added permissions. Please check it out

**Comment by gabitoesmiapodo** [comment]
@igorbarinov 

It's fixed, thank you.
